### ISSUE TITLE
Naming 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/WaterAgeNeutralHabitats#12]
- [x] See all names in dictionaires folder in the server : in dictionaries.
- [x] Design stratgies dropdown : "Full scenario" first, selected by default, and bold (or capitals)
- [x] Rename "Conervative ops" and "radical ops" in "Conservative scenario" and "Radical scenario"

- [x] "Baseline" > "Current"
- [x] Timeseries en 1 mot

- [x] "Compare urban fabric types" [instead of “Compare Landmarks”]

- [x] Rename landmarks everywhere with "Urban Fabric Types" and name them :

- Single-family Houses  (only if really necessary “Single-family H.")
- Open Block Housing  (only if really necessary "Open Block H.")
- Slabs
- Industry

**Comment by charlottegiseleweil** [comment]
Other naming changes from researchers ?

**Comment by pbenettin** [comment]
Hello @charlottegiseleweil and @sbancal. I have now included two data tables in the ENAC server [...]\data_4_visualization\dictionaries, which will hopefully clarify naming and the associated variables. Some table entries will be updated but the format should not change. Can you let me know if the table is in a good format for you? Any suggestion and best practice is welcome.
