### ISSUE TITLE
Timeseries : highlights a few key dates

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/WaterAgeNeutralHabitats#13]
- [x] Paolo to provide 4-5 dates / periods
- [x] to highlight v grey line -> 0a715d5d5961779744ba0c96ed6fe6a13e14df16
- [x] Range highlights for the "dry seasons" -> 0a715d5d5961779744ba0c96ed6fe6a13e14df16

**Comment by pbenettin** [comment]
Hello @charlottegiseleweil and @sbancal, 

The dates you identified are already good and we would not add others. 

- Can you just make the color of the no rain period in light gray instead of yellow? 
- We noticed that the text 'no rain' moves around when we hoover on it
