### ISSUE TITLE
Display Watersheds

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/WaterAgeNeutralHabitats#17]
- [x] Provide watersheds data (researchers)
- [x] Method to display Gpkg functional > but unsuccessful in deployment via Docker. :( :( :( 
- [x] Revert GPKG commit.
- [x] Method to display GeoJSON directly
- [x] Convert watersheds to GeoJSON + Display (on map2)
- [x] Convert rivers to GeoJSON + Display (on map2)

**Comment by charlottegiseleweil** [comment]
To confirm it's ok/how to select
>> in #21 Design meeting before closing -
