### ISSUE TITLE
Non-cumulative Comparable timeseries

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/WaterAgeNeutralHabitats#25]
- [x] Paolo to provide non-cumulative data 
- [x] Copy data timeseries @charlottegiseleweil 
- [x] Display non-cumulative values (P on top, rest on bottom such as :
https://echarts.apache.org/examples/en/editor.html?c=grid-multiple )

- [x] Display P, Q, ET, L separated
- [ ] #30
- [x] Display S as well ?

Bonus feature (low prio)

- [ ] Toggle cumulative fluxes vs. not

**Comment by pbenettin** [comment]
For @sbancal @charlottegiseleweil 
- The non-cumulative data are now in files called [SimulationName]/Outputs/timeseries2.csv (Note the '2' in the file name will disappear in the future, but here I introduced it to avoid overwriting the previous file)
- More info are in the (now updated) readme.md file
- Important note: timeseries variables have a different naming convention now. What used to be e.g. P is now Pcum (to clarify it is cumulative) while P now means non-cumulative. Same convention for variables Q, ET, L. The variable S has only non-cumulative version.

**Comment by charlottegiseleweil** [comment]
thanks @pbenettin ! 

Do I understand well that all the data previously contained in timeseries.csv is still in their under {Variable}cum columns?

In that case can we ask you to replace directly the timeseries.csv with the new ones, avoiding duplicate data and versioning with implicit names ("timeseries2.csv" is noot good practice :) )

**Comment by pbenettin** [comment]
Ok @charlottegiseleweil @sbancal 

You will find everything under the (new) files timeseries.csv. I've also updated the readme.
