### ISSUE TITLE
Layout 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/WaterAgeNeutralHabitats#28]
- [x] (i) button AFTER title; not before
- [x] Add a button "See intro" at the end of the "About" section. 

- [x] General Layout
![Screenshot 2022-03-07 at 15 36 41](https://user-images.githubusercontent.com/18381609/157054711-73ff4bd3-cf04-40f5-8c6a-a6c07d78880b.png)

- [x] Landmark selector (with shapes from scatterplot next to name) and radiobuttons replaced by SVGs provided [here](https://drive.google.com/drive/u/0/folders/1BcAI8X12OVCTUj641Uni_i5iv5p9t_6C)
- [x] Landmark selector should have the symbol/shape of scatterplots!
- [x] Remove paragraph text on the dashboard - 
- [x] Switch scatterplot & timeseries + map bigger in height and square
- [ ] #33

- [x] Conservative/Radical dropdowns with correct labels (from strategies_naming_convention.csv)
- [x] by default Full scenario on both
- [x] Full scenario in **bold**

- [x] About overlay (menu from left, overlaying)

InfoTooltips: 
- [x] Speech bubbles next to mapVariables 
- [x] scheechBubble style ≠ info style
- [x] and info style darker

**Comment by sbancal** [comment]
Tout est checked, excepté le point "no scroll" qui est déporté dans une autre Issue.
