### ISSUE TITLE
Timeseries 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/WaterAgeNeutralHabitats#30]
- [x] Remove S.
- [x] Display for 0, R1 (separate by flux)
- [x] Rename"intense rain" markers.

- [x] Make date selector appear on all 4 timeseries.
- [x] Remove range selector (Zoom button duplicate functionality)
- [ ] #34 Display lines for R2

Bonus

- [ ] #34 Toggle cumulative vs. not

**Comment by pbenettin** [comment]
Hi @charlottegiseleweil @sbancal, can you reorder the timeseries plots to have from top to bottom: rainfall (P), surface runoff (Q), evapotranspiration (ET), soil leakage (L)?

**Comment by charlottegiseleweil** [comment]
@pbenettin it's not very readable now that we inverted axis if we put P on top.. If we invert axis to have P going down, shouldn't it be in the bottom ??

<img width="1181" alt="Screenshot 2022-03-17 at 10 40 42" src="https://user-images.githubusercontent.com/18381609/158781342-977e4896-8755-4a62-9206-edf837532fc3.png">
<img width="1001" alt="Screenshot 2022-03-17 at 10 41 00" src="https://user-images.githubusercontent.com/18381609/158781398-35385893-a555-48e4-8ef5-7cc5e3d5e82c.png">

**Comment by charlottegiseleweil** [comment]
<img width="1001" alt="Screenshot 2022-03-17 at 10 42 03" src="https://user-images.githubusercontent.com/18381609/158781590-264f7006-f3f1-4e63-8d8e-1370d6372828.png">
classci view is P on bottom if we put the axis in that direction

**Comment by sbancal** [comment]
qqch pour moi ici @charlottegiseleweil ?

**Comment by pbenettin** [comment]
Hello @charlottegiseleweil and @sbancal, I confirm that the timeseries order should be, from top to bottom: rainfall (P), surface runoff (Q), evapotranspiration (ET), soil leakage (L).

![image](https://user-images.githubusercontent.com/29303258/159242271-646083fb-b8ba-4fd7-b0e8-f290ef86c973.png)

I know it is inefficient/strange from a data visualization view point, but this is how a hydrologist would show this data and it is important that we keep it that way.
