### ISSUE TITLE
Timeseries

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/WaterAgeNeutralHabitats#34]
- [x] Display lines for R2

Bonus :
- [ ] Toggle cumulative vs. not ➡️ #42

**Comment by charlottegiseleweil** [comment]
@sbancal we can't see the data for R1, is it normal ?

**Comment by sbancal** [comment]
It's not really easy to see because 0 and R1 are almost the same. Some design strategies have more differences than others.

I changed the line style. Now it's a different color instead of same color dashed.

**Comment by sbancal** [comment]
Bonus have been moved to dedicated Issue -> not for this milestone.
