### ISSUE TITLE
On ne voit plus les maps!!

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/WaterAgeNeutralHabitats#36]
Dans certains cas, au chargement de la page, les overlay images n'apparaissent pas.
Il faut p.ex. changer la date sélectionnée pour forcer le chargement de celles-ci.

**Comment by sbancal** [comment]
@charlottegiseleweil 
Pour ma part, je vois bien les maps ... au sens Leaflet.
Pour ce qui est des Overlay images, on ne la voit que dans Existing conditions par défaut, parce que le Design strategy choisi par défaut n'a pas encore d'image fournie.
Lorsqu'on passe à un autre design strategy, alors l'overlay image arrive bien.

... au passage, penser a shift-reload lorsqu'il y a une nouvelle release que vous testez ... ça oblige le navigateur à clearer son cache.

merci de repréciser si il y a effectivement un bug que je n'ai pas vu.
