### ISSUE TITLE
Maps : old layers not removed

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/WaterAgeNeutralHabitats#4]
When playing around ... apparently some layers (*.jpg) are note removed.
This is visible in 2 ways : 
+ when focusing on a specific landmark, unzoom ... we see a previous jpg still visible.
+ when adjusting the opacity ... we don't see the map behind, but an other jpg.

**Comment by charlottegiseleweil** [comment]
I believe this is fixed with my commit  7c6ce8126815cfb1d963a159ef138e74bd23f14f (would you please double check @sbancal that it fixes what you meant?)
