### ISSUE TITLE
Can't find some geojson anymore

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/WaterAgeNeutralHabitats#44]
I flushed all raw & preprocessed data and am trying to reproduce everything using our pipeline.

`copy_geojsons.py` script copies `data/raw/["elements", "Panke", "landmarks"]/*.geojson` to corresponding folder in `data/preprocessed`.

But I can't find anything about these files in `copy_data.py`.

I Can't either find any `*.geojson` in `ENACdrives/proj-wanhabitats/data_4_visualization` ... So where does it come from ?

Could it be set so that we can reproduce everything from scratch ? Where these files did come from ?

thx

**Comment by sbancal** [comment]
btw ... I'm not stuck, since I can get these files from CDN (or from my backups)

**Comment by charlottegiseleweil** [comment]
I converted manually these files from SHP that Cédric had sent - so they are a different pipeline. Can you copy them back @sbancal ?

**Comment by charlottegiseleweil** [comment]
tu te souviens quand même que tu avais fait le script `copy_geojsons.py `? Doesn't this answer the question ?
