### ISSUE TITLE
Timeseries

### ISSUE THREAD

**Issue by pbenettin** [EPFL-ENAC/WaterAgeNeutralHabitats#45]
Hello @sbancal and @charlottegiseleweil,

thanks to the new visualization, I realized there was a shift of one day in the non-cumulative timeseries. I have now corrected this shift and uploaded the corrected timeseries on the server.

**Comment by pbenettin** [comment]
(And I also wanted to confirm that we still would like to have all 3 timeseries superimposed)

**Comment by sbancal** [comment]
- Timeseries data has been updated 👍🏼 
- The tooltip content not yet...
