### ISSUE TITLE
Review Layout & timseries legend (no scroll)

### ISSUE THREAD

**Issue by cedricwehrle** [EPFL-ENAC/WaterAgeNeutralHabitats#53]
Design priorities

- [x] v-around to avoid white space between controls column and maps
- [x] Timeseries cropped tooltip
- [x] y_axis_labels (bug)

- [x] No scroll (to be able to pick dates at the bottom)
- [ ] Dates selector on top in the timeseries if possible ? ➡️  won't do, see [comment](https://github.com/EPFL-ENAC/WaterAgeNeutralHabitats/issues/53#issuecomment-1123308824)
- [x] Titles (water fluxes in time/space) but with NO SCROLL ?
- [x] Improve legend for timeseries (see below)
- [x] Improve layout : 
  - [x] col-2 : landmarksSelectors, 
  - [x] col-2 : 
      - [x] row-half : mapControls + Legend, 
       - [x] row-half : timeseriesLegend
  - [x] col-8 : 
       - [x] row half : maps
       - [x] row-half : timeseries
 
- [x] opacity width needs to be fixed by Legend
- [x] Maps colorscales width must adjsut so the right-most value is never hidden.
- [x] Suggested : the controls on the left are separated from the plots to the right by using a grey background.

- [x] Externalize scatterplot in its own page with button

![Screenshot 2022-04-27 at 12 27 18](https://user-images.githubusercontent.com/18381609/165498441-0aa31cfb-ca80-4ac7-a454-4678944725cb.png)

LEGEND: 
Precipitation (i)

Surface Runoff (i)
 Now - Cons. - Rad.

Evapotranspiration (i)
 Now - Cons. - Rad.

Soil Leakage (i)
 Now - Cons. - Rad.

**Comment by sbancal** [comment]
Since layout has no scroll anymore, I didn't move dates selector on top in the timeseries.
If absolutely needed, please let me know. @cedricwehrle
