### ISSUE TITLE
Add Explanatory infoTooltips upon hover (i)

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/WaterAgeNeutralHabitats#9]
- [x] remove Existing condition (i)

### Conservative Scenario (i) 
The Conservative Scenario comprises a series of design strategies which can be easily implemented. They are related to publicly owned land only and don’t impact on the current use of space (e.g. de-paving public, sealed surfaces).

#### Design strategies
- Transform parking lots - Surfaces devoted to car and truck parking are de-paved. Asphalt and pavement are replaced with stabilized grass surfaces. 

- Transform sidewalks - Sidewalks are transformed both in their width and their depth. Sealed surfaces are replaced with more permeable material, and rows of trees are systematically planted along sidewalks. 

- Transform public buildings’ open spaces - Open spaces located on the grounds of public buildings (schools, police stations, etc.) are heavily transformed through the depaving of most sealed surfaces and the planting of new vegetation.

- Regenerate lawns - Lawn surfaces, mainly located in front of or in between collective housing buildings, as well as inside private gardens are to be more densely vegetated. Grass is let to grow longer, and more shrubs are planted on underused areas.

### Radical Scenario (i)
The Radical Scenario comprises a series of design strategies entailing radical modifications in space. They are related to public and private land and may impact on the current use of space (e.g. de-paving/revegetating/tree planting public and private surfaces).

#### Design strategies

- Transform parking lots - Surfaces devoted to car and truck parking are de-paved. Asphalt and pavement are replaced with stabilized grass surfaces, and trees are planted between parking spots.

- Transform sidewalks - Sidewalks are transformed both in their width and their depth. Sealed surfaces are replaced with more permeable material, and rows of trees are systematically planted along sidewalks. 

- Transform public buildings’ open spaces - Open spaces located on the grounds of public buildings (schools, police stations, etc.) are heavily transformed through the depaving of most sealed surfaces and the planting of new vegetation.

- Regenerate lawns - Lawn surfaces, mainly located in front of or in between collective housing buildings, as well as inside private gardens are to be more densely vegetated. Grass is let to grow longer, and more shrubs are planted on underused areas.

- Depave secondary streets - Secondary streets receiving only local car traffic are de-paved. Asphalt and pavement are replaced with more permeable gravel surfaces, still allowing for slow motorized mobility.

- Vegetate flat roofs - Flat roofs are systematically transformed into «green» roofs capable of temporarily storing water. Runoff from the vegetated roofs will directly infiltrate in the ground around the building. 

- Transform residual sealed surfaces - Sealed surfaces are defined as «residual» if they are neither used for parking, walking, driving, recreation or storing purposes. These surfaces are to be de-paved and planted with vegetation, while allowing for multiple uses.

### Water fluxes

- [x] *Add title "Water fluxes" before the mapVariables selection div*

- [x] after each mapVariable, replace the speechbubble by (i) with contents from "description" column in tables_fluxes.csv*

LSrfn
Evap
PrcL3
SWCup

Daily surface runoff, mainly coming from low-permeability surfaces
Daily evapotranspiration flux, including soil and canopy evaporation and plant transpiration
Daily leakage from the upper soil to groundwater
Daily volumetric water content in the upper soil layers (accessible by vegetation, does not include groundwater)

#### Water fluxes (i)
The maps display distribution of the water fluxes on a given day, according to the simulated existing condition and scenarios. These maps have spatial resolution 1 meter and size 250x250. 

Key Functionalities:

* Change the selected date at the bottom of the timeseries to see the spatial distribution in different days
* Select a different symbol in the left menu to switch to a different urban fabric type
* Change the displayed variable by selecting the water flux below
* Change maps opacity with the slider below
* Select design strategy [...] PAOLO PLEASE DESCRIBE?

## Timeseries (i) :

- [x] Rename "Fluxes over time" by "Water fluxes in time"

Daily evolution of the water fluxes over a 2-year period, according to the simulated existing condition and scenarios. A dry period is highlighted in grey; two major storm events are highlighted through a dashed line.

- [ ] PAOLO: HERE WE ARE LACKING A DESCRIPTION OF THE VARIABLES IN THE TIMESERIES NO?

Key Functionalities:
 * Shift the selected date to update the maps to this specific date
 * Click on the legend to turn timeseries on/off
 * Zoom in the chart with the zoom buttons in the upper right corner
 * Download the chart as an image with the download button in the upper right corner

## Scatterplot (i) :
Fraction of surface runoff [or evapotranspiration or soil leakage, if they will be included] production against the fraction of permeable surface area. Each marker indicates an individual design strategy for an urban fabric type.

Key Functionalities:
 * Click on any urban fabric type to select/de-select the corresponding points
 * Zoom in the chart with the zoom buttons in the upper right corner
 * Download the chart as an image with the download button in the upper right corner

**Comment by pbenettin** [comment]
Hello @charlottegiseleweil and @sbancal, the project title (that currently reads "Berlin Water Age Neutral Habitats") should become:

**URBAN WATER CYCLE RE-DESIGN**
_Berlin_

(note the uppercase, bold and italic fonts). Cédric is preparing the short text that will explain the project when clicking on (i)

**Comment by cedricwehrle** [comment]
When you click on (i), the following "About" text should appear:

This work is part of the Water-Age-Neutral Habitats: Re-designing the urban water cycle for a renewable city-territory research project, conducted at EPFL. This interdisciplinary project is funded by the ENAC Cluster Grants 2020 - Sustainable Territories, with modelling done in collaboration with Chris Soulsby and his team at IGB Berlin. This website is created through the ENAC Cluster Grant Data Valorisation program.  

Research Team:
Martina Barcelloni Corte, EPFL, Laboratory of urbanism LAB-U
Paolo Benettin, EPFL, Laboratory of ecohydrology ECHO
Cédric Wehrle, EPFL, Laboratory of urbanism LAB-U

Data visualization Team:
Charlotte Weil, EPFL, IT4Research
Samuel Bancal, EPFL, IT4Research

***

Furthermore, we have made a list of adjustments concerning the three welcome pages:

**0 Welcome**
In general the illustration is too large and the title not enough. Ideally one's eyes should be drawn to the title before the illustration.
- please change the maximum size of the diagram to a smaller size (as a guide, the text of the illustration needs to be smaller than the title)
- please convert the body of the text in same font/size of title (eventually enlarge the overall size)
- if the spacing of a larger title is an issue one could consider centering the title and the text, and putting the image underneath?

**1 Watershed page** 

- please erase the title ("Re-designing [...] habitats")
- for more clarity in the map, please erase the sub-watershed lines (thin white lines) from the image. The rest is fine. 

**3 Urban Fabric Types**

- here we really need to have the correct (ie complete) naming of the urban fabric types (Housing Slabs, Single Family Housing, Industry, and Open Block Housing). On the current layout there should be enough horizontal space for it.

**Comment by pbenettin** [comment]
Hello @charlottegiseleweil and @sbancal,

I list here the texts for the infoTooltips

##  about tab (i) 

Cédric already sent you the about text. Below it, I'd like to include the following methods:

**Methods**

We computed the main water fluxes in space and time through the ecohydrological model EcH2O-iso, using the data and parameterization from Gillefalk et al., (2021). The implementation of the different design strategies resulted in changes to the land covers and associated model parameters. The data show results from 11 design strategies per urban fabric type. Simulations were run at daily time steps, from 30 November 2017 to 30 November 2019 (2 years), after a spinup period of 1 year.

Gillefalk, M., Tetzlaff, D., Hinkelmann, R., Kuhlemann, L.-M., Smith, A., Meier, F., Maneta, M. P., and Soulsby, C.: Quantifying the effects of urban green space on water partitioning and ages using an isotope-based ecohydrological model, Hydrol. Earth Syst. Sci., 25, 3635–3652, https://doi.org/10.5194/hess-25-3635-2021, 2021.

##  Conservative Scenario (i) and Radical Scenario (i) 

(No info text on Existing Condition) 

I report here the text that Cédric had uploaded on google drive:

The Conservative Scenario comprises a series of design strategies  which can be easily implemented. They are related to publicly owned land only and don’t impact on the current use of space (e.g. de-paving public, sealed surfaces).

The Radical Scenario comprises a series of design strategies entailing radical modifications in space. They are related to public and private land and may impact on the current use of space (e.g. de-paving/revegetating/tree planting public and private surfaces).

## info on water fluxes in the top left panel

They should be info (i) and not speech bubbles. The text is provided for each variable within the dictionary table_fluxes.csv

## WATER FLUXES IN TIME (i)

The title of the timeseries should be "WATER FLUXES IN TIME", with an info (i) next to the title.  The info text should be: 

Daily evolution of the water fluxes over a 2-year period, according to the simulated existing condition and scenarios. A dry period is highlighted in grey; two major storm events are highlighted through a dashed line.

Key Functionalities:
- Shift the selected date to update the maps to this specific date
- Click on the legend to turn timeseries on/off
- Zoom in the chart with the zoom buttons in the upper right corner
- Download the chart as an image with the download button in the upper right corner

## WATER FLUXES IN SPACE (i)

We would like to give a title to the maps: "WATER FLUXES IN SPACE", with an info (i) next to the title. The info text should be: 

Spatial distribution of the water fluxes on a given day, according to the simulated existing condition and scenarios. 

Key Functionalities:
- Change the selected date at the bottom of the timeseries to see the spatial distribution in different days
- Select a different symbol in the left menu to switch to a different urban fabric type
- Change the displayed variable by selecting from the left menu
[I'm sure I forgot some... ]

##  Scatterplot (i)

Fraction of surface runoff [_or evapotranspiration or soil leakage, if they will be included_] production against the fraction of permeable surface area. Each marker indicates an individual design strategy for an urban fabric type. 

## Speech Bubbles?

Right now there is no speech bubble. We would really like to include a short analysis of the results/conclusions, but we are unsure where to put it. Do you think a button that opens a "Main conclusions" page would be effective?

**Comment by charlottegiseleweil** [comment]
@pbenettin 

## Conservative Scenario (i) and Radical Scenario (i)
Don't these buttons should also contain the descriptions of each of the interventions ?

**Comment by pbenettin** [comment]
@charlottegiseleweil @sbancal 

This is a good point! We had not thought about it yesterday, but this is the right place where to include those descriptions. You can take them directly from the dictionary `strategies_naming_convention.csv`. It could be a list {short_name}: {full_description}

Thanks for this idea!

**Comment by charlottegiseleweil** [comment]
@pbenettin - it's not clear where you'd like the additional title "Water fluxes in space". That's also inconsistent with the current layout... Do you really need this subtitle?

**Comment by charlottegiseleweil** [comment]
@pbenettin can you check/validate the texts above (in the original issue, updated) ?

**Comment by pbenettin** [comment]
Hi @charlottegiseleweil, yes we think having a title for the maps plot is a very important improvement. We had thought about something like this (in the sketch there is Existing condition 3 times just because we copied/pasted the same image 3 times for simplicity)

![tmp](https://user-images.githubusercontent.com/29303258/163356925-5df96b87-c154-4d9a-96e4-0e9d35348411.png)

**Comment by pbenettin** [comment]
And sorry @charlottegiseleweil I do not understand what you mean by 

> can you check/validate the texts above (in the original issue, updated) ?

**Comment by sbancal** [comment]
@pbenettin @charlottegiseleweil I think / hope / consider I did everything in this issue.

I let it open since there are still 2 open questions to @pbenettin (I copy both here to help find them) : 

- [ ]  PAOLO: HERE WE ARE LACKING A DESCRIPTION OF THE VARIABLES IN THE TIMESERIES NO?
- [ ] Select design strategy [...] PAOLO PLEASE DESCRIBE?

**Comment by pbenettin** [comment]
@sbancal @charlottegiseleweil thank you very much for already implementing all these infoTooltips. 

> PAOLO: HERE WE ARE LACKING A DESCRIPTION OF THE VARIABLES IN THE TIMESERIES NO?

Rather than adding a description, is it possible to give a title to the different subplots (or structure the legend through titles) as in the sketch below?

![legends](https://user-images.githubusercontent.com/29303258/163405845-c8853bfd-90d5-434c-aeb8-341185eaf4ce.png)

> Select design strategy [...] PAOLO PLEASE DESCRIBE?

I think there is no need for the **Water fluxes (i)** tooltip and the title could become **Water fluxes selection**. The key functionalities should all be in the tooltip next to WATER FLUXES IN SPACE. 

**NOTE:** I think the text within this tooltip has been misplaced (it currently shows the text of the scatterplot), so I re-write here the full text that should appear under the WATER FLUXES IN SPACE tooltip:

Spatial distribution of the water fluxes on a given day, according to the simulated existing condition and scenarios. Each map has a spatial resolution of 1 meter and size 250x250 m.

Key Functionalities:

- Change the selected date at the bottom of the timeseries to see the spatial distribution in different days
- Select a different symbol in the left menu to switch to a different urban fabric type
- Change the displayed variable by selecting the water flux from the left menu
- Change maps opacity with the slider from the left menu
- Highlight one urban element by using the dropdown menu "Element highlight"
- Change the displayed design strategy by using the dropdown menu "Design strategy"

**Comment by pbenettin** [comment]
@sbancal and @charlottegiseleweil the text in the scatterplot shows a comment that was not meant to be displayed (sorry, I should have made clear that that was a comment). The tooltip should be slightly modified:

Fraction of surface runoff production against the fraction of permeable surface area. Each marker indicates an individual design strategy for an urban fabric type.

**Comment by pbenettin** [comment]
@sbancal and @charlottegiseleweil possibly a little bug on the WATER FLUXES IN TIME tooltip (the text appears truncated):

![tmp](https://user-images.githubusercontent.com/29303258/163409173-6d613027-9518-471a-b7b5-c7a3f0d033d0.png)

**Comment by pbenettin** [comment]
@sbancal and @charlottegiseleweil, I think there is one residual thing suggested by Cédric that has not been implemented yet. I report it here:

- Intro, page 1 (Watershed): the title "Re-Designing [...] Habitats" should be removed.
- Intro, page 1 (Watershed): the last version of the text that was uploaded on google drive was slightly shorter:

Knowledge of how to articulate the “urban transition” is urgently needed today. Urbanization is on a steadily growing trend that impacts the water cycle as a whole. However, while the effects of urbanized/urbanizing areas on water quantity (how much water) have been well studied for flood prevention, other effects – such as those related to water quality (which water) – are mostly unknown. Taking hold from the most recent developments in the fields of environmental science and urbanism, we propose to study the impact of urban planning on the water cycle, exploring the possibility of lowering – through design – net impacts on the water cycle of urbanized areas. This project’s case study lies within the Panke river catchment in Berlin (DE).
